---
- name: Download R
  get_url: >
    url=https://cran.r-project.org/bin/macosx/R-3.3.1.pkg
    dest={{ downloads_directory }}/R-3.3.1.pkg

- name: Install R
  command: >
    chdir={{ downloads_directory }}
    installer -package R-3.3.1.pkg -target /
  become: yes
