---
- name: Download fish
  get_url: >
    url=https://fishshell.com/files/2.5.0/fish-2.5.0.pkg
    dest={{ downloads_directory }}/fish-2.5.0.pkg

- name: Install fish
  command: >
    installer -package {{ downloads_directory }}/fish-2.5.0.pkg -target /
    creates=/usr/local/bin/fish
