---
- name: Check out my dotfiles repository
  git:
    repo: git@github.com:mpereira/dotfiles.git
    dest: "{{ home_directory }}/.dotfiles"
    update: no

- name: Load environment variables
  include_vars:
    file: environment.yml
    name: environment_variables

- debug: var=environment_variables

- name: Install dotfiles
  env: environment_variables
  environment: "{{ environment_variables }}"
  command: rake sync
  args:
    chdir: "{{ home_directory }}/.dotfiles"
