---
# get_url fails to download because of a bug with SSL handling.
# https://github.com/ansible/ansible/issues/23642
- name: Download Prey
  command: >
    chdir={{ downloads_directory }}
    wget -nc -q https://downloads.preyproject.com/prey-client-releases/node-client/{{ prey_version }}/{{ prey_pkg }}
- name: Load API key
  include_vars:
    file: api_key.yml
    name: api_key

- name: Install Prey
  shell: >
    API_KEY={{ api_key.prey_api_key }} installer -package {{ downloads_directory }}/{{ prey_pkg }} -target /
  become: yes
