---
- name: Download Silverlight
  get_url: >
    url=http://silverlight.dlservice.microsoft.com/download/6/B/8/6B885B0B-73D4-4BCE-BFFF-154B4A402D22/20913.00/Silverlight.dmg
    dest={{ downloads_directory }}/Silverlight.dmg

- name: Mount Silverlight image
  command: >
    chdir={{ downloads_directory }}
    hdiutil attach Silverlight.dmg
    creates=/Volumes/Silverlight

- name: Install Silverlight
  command: >
    installer -package /Volumes/Silverlight/Silverlight.pkg -target /
    creates=/Applications/Microsoft\ Silverlight
  become: yes

- name: Unmount Silverlight image
  command: hdiutil detach /Volumes/Silverlight
