---
- name: Download Python 3
  get_url: >
    url=https://www.python.org/ftp/python/3.6.0/python-3.6.0-macosx10.6.pkg
    dest={{ downloads_directory }}/python-3.6.0-macosx10.6.pkg

- name: Install Python 3
  command: >
    installer -package {{ downloads_directory }}/python-3.6.0-macosx10.6.pkg -target /
  become: yes
