---
- name: Download Haskell
  get_url: >
    url=https://www.haskell.org/platform/download/2014.2.0.0/Haskell%20Platform%202014.2.0.0%2064bit.signed.pkg
    dest={{ downloads_directory }}/Haskell\ Platform\ 2014.2.0.0\ 64bit.signed.pkg

- name: Install Haskell
  command: >
    installer -package {{ downloads_directory }}/Haskell\ Platform\ 2014.2.0.0\ 64bit.signed.pkg -target /
    creates=/Library/Haskell
  become: yes
