---
- name: Download Node.js
  get_url:
    url: https://nodejs.org/dist/v{{ node_version }}/{{ node_pkg }}
    dest: "{{ downloads_directory }}/{{ node_pkg }}"

- name: Install Node.js
  command: >
    chdir={{ downloads_directory }}
    installer -package {{ node_pkg }} -target /
  become: yes
