---
- name: Download Qt5
  get_url: >
    url="{{ qt5_image_url }}"
    dest="{{ qt5_image_path }}"
    checksum="md5:3d940877ea3dd22c095463bcdf6aa966"

- name: Get {{ qt5_app_directory }} stats
  stat:
    path: "{{ qt5_app_directory }}"
  register: qt5_app_directory_stat

- name: Mount Qt5 image
  command: >
    hdiutil attach -noverify {{ qt5_image_path }}
    creates="{{ qt5_volume_path }}"
  when: not qt5_app_directory_stat.stat.exists

- name: Get {{ qt5_volume_path }} stats
  stat:
    path: "{{ qt5_volume_path }}"
  register: qt5_volume_path_stat

- name: Create {{ qt5_app_directory }}
  command: >
    cp -R "{{ qt5_volume_path }}/{{ qt5_app_name }}" /Applications
    creates="{{ qt5_app_directory }}"
  become: yes

- name: Unmount Qt5 image
  command: hdiutil detach "{{ qt5_volume_path }}"
  when: qt5_volume_path_stat.stat.exists
