---
- name: Download Dash
  get_url:
    url: http://newyork.kapeli.com/{{ dash_zip }}
    dest: "{{ downloads_directory }}/{{ dash_zip }}"

- name: Extract {{ dash_zip }} archive
  command: >
    chdir={{ downloads_directory }}
    unzip {{ dash_zip }} -d {{ dash_directory }}
    creates={{ dash_directory }}

- name: Copy {{ dash_app }} to Applications directory
  command: >
    cp -R {{ downloads_directory }}/Dash/{{ dash_app }} /Applications
    creates=/Applications/{{ dash_app }}
  become: yes
